package com.example.maadminiproject.data.models

/**
 * Data model representing an activity log entry generated by the Smart Home system.
 *
 * @property logId Unique identifier for the log entry.
 * @property deviceId The ID of the device associated with this activity, if applicable.
 * @property deviceName The name of the device associated with this activity.
 * @property action The specific action performed (e.g., "Device Turned On", "Schedule Created").
 * @property description A detailed description of the activity.
 * @property timestamp The time when the activity occurred.
 * @property performedBy The user or system process that triggered the activity.
 */
data class ActivityLog(
    val logId: String = "",
    val deviceId: String = "",
    val deviceName: String = "",
    val action: String = "",
    val description: String = "",
    val timestamp: Long = 0L,
    val performedBy: String = "",
)
